Feature: Create a Youth
  In order to track youths
  As a leader
  I want to be able to create youths in the system

  Scenario: User fills out youth create form, incorrectly
    Given I am authenticated as "hall.jake.a@gmail.com"
    And I am on "youths/create"
    And I fill in "first_name" with "Jake"
    And I press "Create"
    Then I should see "is required"

  Scenario: User fills out youth create form, incorrectly
    Given I am authenticated as "hall.jake.a@gmail.com"
    And I am on "youths/create"
    And I fill in "first_name" with "Jake"
    And I fill in "last_name" with "Hall"
    And I press "Create"
    Then I should see "is required"

  Scenario: User fills out youth create form, incorrectly
    Given I am authenticated as "hall.jake.a@gmail.com"
    And I am on "youths/create"
    And I fill in "first_name" with "Jake"
    And I fill in "last_name" with "Hall"
    And I fill in "address_line1" with "15 Queens Court"
    And I press "Create"
    Then I should see "is required"

  Scenario: User fills out youth create form, incorrectly
    Given I am authenticated as "hall.jake.a@gmail.com"
    And I am on "youths/create"
    And I fill in "first_name" with "Jake"
    And I fill in "last_name" with "Hall"
    And I fill in "address_line1" with "15 Queens Court"
    And I fill in "postal_town" with "Epsom"
    And I press "Create"
    Then I should see "is required"

  Scenario: User fills out youth create form, correctly
    Given I am authenticated as "hall.jake.a@gmail.com"
    And I am on "youths/create"
    And I fill in "first_name" with "Jake"
    And I fill in "last_name" with "Hall"
    And I fill in "address_line1" with "15 Queens Court"
    And I fill in "postal_town" with "Epsom"
    And I fill in "postal_code" with "KT19 9RJ"
    And I press "Create"
    Then I should see "has been created"

  Scenario: User fills out youth create form, check all the data is kept
    Given I am authenticated as "hall.jake.a@gmail.com"
    And I am on "youths/create"
    And I fill in "title" with "~~Title"
    And I fill in "first_name" with "~~First Name"
    And I fill in "middle_names" with "~~Middle Names"
    And I fill in "last_name" with "~~Last Name"
    And I fill in "dob" with "1992-05-14"
    And I fill in "telephone" with "~~01234567890"
    And I fill in "email" with "email@example.com"
    And I fill in "patrol_name" with "~~Patrol"
    And I select "Northern Irish" from "nationality_id"
    And I select "Hindu" from "faith_id"
    And I select "Irish" from "ethnicity_id"
    And I select "Yes" from "swim"
    And I select "Yes" from "bannedFirearms"
    And I fill in "address_line1" with "~~Address Line 1"
    And I fill in "address_line2" with "~~Address Line 2"
    And I fill in "address_line3" with "~~Address Line 3"
    And I fill in "address_line4" with "~~Address Line 4"
    And I fill in "postal_town" with "~~Town"
    And I fill in "postal_county" with "~~County"
    And I fill in "postal_code" with "KT19 9RJ"
    And I fill in "doctor_name" with "~~Dr. Name"
    And I fill in "nhs_number" with "~~NHS Number"
    And I fill in "dietary_needs" with "~~Diet"
    And I fill in "medical_info" with "~~Medical"
    And I fill in "disability_notes" with "~~Disability Notes"
    And I press "Create"
    Then I should see "has been created"
    And I should see the field "title" filled with "~~Title"
    And I should see the field "first_name" filled with "~~First Name"
    And I should see the field "middle_names" filled with "~~Middle Names"
    And I should see the field "last_name" filled with "~~Last Name"
    And I should see the field "dob" filled with "1992-05-14"
    And I should see the field "telephone" filled with "~~01234567890"
    And I should see the field "email" filled with "email@example.com"
    And I should see the field "patrol_name" filled with "~~Patrol"
    And I should see the field "address_line1" filled with "~~Address Line 1"
    And I should see the field "address_line2" filled with "~~Address Line 2"
    And I should see the field "address_line3" filled with "~~Address Line 3"
    And I should see the field "address_line4" filled with "~~Address Line 4"
    And I should see the field "postal_town" filled with "~~Town"
    And I should see the field "postal_county" filled with "~~County"
    And I should see the field "postal_code" filled with "KT19 9RJ"
    And I should see the field "doctor_name" filled with "~~Dr. Name"
    And I should see the field "nhs_number" filled with "~~NHS Number"
    And I should see the field "dietary_needs" filled with "~~Diet"
    And I should see the field "medical_info" filled with "~~Medical"
    And I should see the field "disability_notes" filled with "~~Disability Notes"